
sqlite3 ../database.db << EOF

CREATE TABLE WM_ITEMS(
ID TEXT PRIMARY KEY NOT NULL,
NAME TEXT NOT NULL,
URL_NAME TEXT NOT NULL
);

CREATE TABLE WF_MISC(
NAME TEXT PRIMARY KEY NOT NULL,
CONTENT TEXT DEFAULT ""
);

EOF